services: 
  nginx:
    image: nginx:stable-alpine
    container_name: api-laravel-nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mysql
    networks:
      - api-laravel-network

  mysql:
    image: mysql:8.0.41
    container_name: api-laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - 33066:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 's3cr3t'
      MYSQL_DATABASE: 'api-laravel-db'
      MYSQL_USER: 'laravel_user'
      MYSQL_PASSWORD: 'laravel_passwd'
    networks:
      - api-laravel-network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: 1000
        PGID: 1000
    container_name: api-laravel-php-fpm
    volumes:
      - ./src:/var/www/html
      - ./php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 9000:80
    networks:
      - api-laravel-network
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  api-laravel-network:

volumes:
  mysql_data: