services: 
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    ports:
      - ${SRV_PORT_HOST}:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0.41
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT_HOST}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: 1000
        PGID: 1000
    container_name: ${APP_NAME}-php-fpm
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
      - ./php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 9009:80
    networks:
      - app-network
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  app-network:
    name: ${APP_NAME}-network

volumes:
  mysql_data: