services: 
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_LARAVEL}-nginx
    ports:
      - ${SRV_PORT}:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0.41
    container_name: ${APP_LARAVEL}-mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: 1000
        PGID: 1000
    container_name: ${APP_LARAVEL}-php-fpm
    volumes:
      - ./src:/var/www/html
      - ./php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 9000:80
    networks:
      - app-network
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  app-network:
    name: ${APP_LARAVEL}-network

volumes:
  mysql_data: